name: EnableFly
version: 1.0
author: Zen Wolf
main: me.zenisbestwolf.enablefly.Main
description: Use /fly to fly in all gamemodes.
default: op
api-version: 1.15
permissions:
    enablefly.fly:
        description: "Allows players to use /fly"
        default: op
commands:
    fly:
        description: Enables/disables fly for the specified player.
        usage: "/<command> [target]"
        permission: enablefly.fly